vars: {
    d2-config: {
      layout-engine: elk
      theme-id: 300
    }
  }
  
title: UFS Coastal Structure {
shape: text
near: top-center
style: {
    font-size: 55
    italic: true
}
}
grid-rows: 2
grid-columns: 2

ocean: "Ocean Models"  {
    ADCIRC
    CICE
    FVCOM
    HYCOM
    MOM
    ROMS
    SCHISM
    WW3
}

atmosphere: "ATM Models" {
    AQM
    FV3
}

infrastructure: "Infrastructure" {
    CDEPS
    CMEPS
    Workflow
}

other: "Other" {
    NOAHMP
    NWM
    PAHM
    GOCART
} 

